spring:
  datasource:
    url: jdbc:postgresql://localhost:2345/ecommerce
    username: postgres
    password: 1234567

  jpa:
    properties:
      hibernate:
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  port: 8080
